### ISSUE TITLE
customizations table is empty

### ISSUE THREAD

**Issue by rupee365** [Overx/viper#1]
customizations
This table is empty. It was giving me error
![image](https://github.com/Overx/viper/assets/171782393/d39e9503-e366-4d26-a8e6-942a0e6d2ce9)

**Comment by rupee365** [comment]
Models are missing

**Comment by Overx** [comment]
The customization table is probably missing a record, you can create a record manually.

**Comment by amiyoghoshstar** [comment]
Yes but lot of models are missing

**Comment by Overx** [comment]
Add the full version in the release
