### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by lucasrohers** [Overx/viper#10]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viper.customizations' doesn't exist
SELECT * FROM `customizations` limit 1

Instalei esta versão do github, mas tenho este erro. No SQL não vejo esta tabela.

**Comment by Overx** [comment]
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viper.customizations' doesn't exist SELECT * FROM `customizations` limit 1
> 
> Instalei esta versão do github, mas tenho este erro. No SQL não vejo esta tabela.

Utilize o comando php artisan migrate, ele vai carregar a tabela que está faltando.
