### ISSUE TITLE
[ERROR] - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by renat473** [Overx/viper#5]
Ao acessar tentar acessar a plataforma estou com este erro como apresentado na imagem.

versão : 

PHP 8.2.11

![image](https://github.com/Overx/viper/assets/1757167/0dd0f602-5cea-4d1e-b218-c9d793b4ba52)

**Comment by levylennon** [comment]
Veja se no seu banco de dados na tabela Layout tem a coluna "expanded_layout"

**Comment by lipematt** [comment]
Tenho o mesmo problema e tenho a coluna na tabela
mysql> describe customizations;
+------------------+-----------------+------+-----+---------+----------------+
| Field            | Type            | Null | Key | Default | Extra          |
+------------------+-----------------+------+-----+---------+----------------+
| id               | bigint unsigned | NO   | PRI | NULL    | auto_increment |
| expanded_layout  | tinyint(1)      | NO   |     | 0       |      
          |
| card_type        | varchar(191)    | NO   |     | default |      
          |
| header_type      | varchar(191)    | NO   |     | default |      
          |
| side_type        | varchar(191)    | NO   |     | default |      
          |
| footer_type      | varchar(191)    | NO   |     | default |      
          |
| primary_color    | varchar(20)     | YES  |     | NULL    |      
          |
| secondary_color  | varchar(20)     | YES  |     | NULL    |      
          |
| background_color | varchar(20)     | YES  |     | NULL    |      
          |
| footer_color     | varchar(20)     | YES  |     | NULL    |      
          |
| created_at       | timestamp       | YES  |     | NULL    |      
          |
| updated_at       | timestamp       | YES  |     | NULL    |      
          |
+------------------+-----------------+------+-----+---------+----------------+
12 rows in set (0.01 sec)

**Comment by Overx** [comment]
`php artisan migrate`
