### ISSUE TITLE
não faz upload de nenhuma iamgem

### ISSUE THREAD

**Issue by lipematt** [Overx/viper#7]
![Imagem do WhatsApp de 2024-03-06 à(s) 16 43 35_e9a8a4c4](https://github.com/Overx/viper/assets/38258130/b71d00f1-7f2b-4787-bc0c-b64453f07b40)
console retorna 
Failed to load resource: the server responded with a status of 401 ()

**Comment by DinhoNunesLC** [comment]
Aplique as permissões 777 a pasta e tente novamente.

**Comment by Overx** [comment]
> ![Imagem do WhatsApp de 2024-03-06 à(s) 16 43 35_e9a8a4c4](https://private-user-images.githubusercontent.com/38258130/310672745-b71d00f1-7f2b-4787-bc0c-b64453f07b40.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTAwNzMsIm5iZiI6MTcxMTUwOTc3MywicGF0aCI6Ii8zODI1ODEzMC8zMTA2NzI3NDUtYjcxZDAwZjEtN2YyYi00Nzg3LWJjMGMtYjY0NDUzZjA3YjQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAzMjI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzJiYzUyNjlmNDlmMTFiYTMyYTMyZGY1N2YzODZiMWY4OTU3NmIxZmEzZWY4OTI2YzFlNGM3YTA4ZGVjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bZVT9iNqIspQz9pkgXN91QyaB23el89sT9xh-oB_-XQ) console retorna Failed to load resource: the server responded with a status of 401 ()

Verifique as permissões da pasta de upload. e também APP_URL no .env, as vezes vc colocou seu site com http, precisa ser https

**Comment by lipematt** [comment]
O erro era no proxy pois estava usando cloudfare

**Comment by ofelipeboaventura** [comment]
Como conseguiu resolver? 
já apliquei permissões 777 na pasta upload, APP_URL tbm já está com https, e na cloudflare o proxy está desativado

**Comment by lipematt** [comment]
Abre seu console do navegador e ve se o erro é de permissão mesmo, deve retornar um 401 depois que tentar subir a imagem, eu resolvi editando middleware TrustProxies pra aceitar o ip do cloudfare mas tambem pode aceitar todos
