### ISSUE TITLE
Uso da Plataforma

### ISSUE THREAD

**Issue by vitorsilveira93** [Overx/viper#9]
Olá, boa noite, além do GGR, tem algum custo para usar esse projeto e fazer funcionar?

**Comment by DinhoNunesLC** [comment]
Ao que eu sei, apenas da VPs, domínio e comissão que se cobra pelo gateway de pagamento.

**Comment by Overx** [comment]
> Olá, boa noite, além do GGR, tem algum custo para usar esse projeto e fazer funcionar?

GGR é dos provedores de jogos, não cobramos nada pela plataforma.
